---
title: 'HLA and HED visualizations'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
  library(here)
  library(tidyverse)
  library(reshape2)
  library(RColorBrewer)
  library(ComplexHeatmap)
})

main_folder <- here()
data_folder <- "/data/alice/melanoma"
```

```{r}
coldata <- read_csv(file.path(main_folder,"clean_metadata.csv"), show_col_types=F)

hla_files <- list.files(path = data_folder, pattern = "*_result.tsv", recursive = TRUE, full.names = TRUE) %>%
  .[grepl("melanoma/[A-Za-z]+-[0-9]{4}", .)]

hla_data_list <- map(hla_files, ~ {
  df <- suppressWarnings(suppressMessages(read_tsv(.x, show_col_types = FALSE)))
  # extract the sample names and dataset
  file_prefix <- str_split(basename(.x), "_")[[1]][1]
  dataset <- str_extract(.x, "(?<=melanoma/)[^/]+")
  # add the sample name as a new column
  df %>% 
    select(-`...1`, -Reads, -Objective) %>%
    mutate(subject = file_prefix, .before="A1") %>%
    mutate(dataset = dataset, .before="subject")
})
hla <- bind_rows(hla_data_list) %>%
  inner_join(.,coldata %>% select(accession), by=c("subject"="accession"))
write.table(hla, file.path(main_folder,"genotypes.csv"), quote = F, sep = ",", row.names = F, col.names = T)


```


# group annotation
```{r}
hla <- read_csv(file.path(main_folder,"genotypes.csv"), show_col_types=F) %>%
  select(-dataset)

coldata <- read_csv(file.path(main_folder,"clean_metadata.csv"), show_col_types=F)

meta <- coldata %>%
  select(accession,response_group,dataset) %>%
  dplyr::rename("subject"="accession", "group"="response_group")

hla.expr <- read_tsv(file.path(main_folder,"mela_ici_tpm.tsv"), show_col_types=F) %>%
  filter(grepl("HLA-A|HLA-B|HLA-C",gene_name)) %>%
  column_to_rownames("gene_name") %>%
  select(any_of(meta$subject))
```

```{r}
alter_fun = list(
    background = function(x, y, w, h) {
      grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "#CCCCCC", col = NA))
    },
    A1 = function(x, y, w, h) {
      grid.rect(x, y, w-unit(0.5, "mm"), h*0.47, vjust = 0, gp = gpar(fill = "#A6CEE3", col = NA))
    },
    A2 = function(x, y, w, h) {
      grid.rect(x, y, w-unit(0.5, "mm"), h*0.47, vjust = 1, gp = gpar(fill = "#1F78B4", col = NA))
    },
    B1 = function(x, y, w, h) {
      grid.rect(x, y, w-unit(0.5, "mm"), h*0.47, vjust = 0, gp = gpar(fill = "#B2DF8A", col = NA))
    },
    B2 = function(x, y, w, h) {
      grid.rect(x, y, w-unit(0.5, "mm"), h*0.47, vjust = 1, gp = gpar(fill = "#33A02C", col = NA))
    },
    C1 = function(x, y, w, h) {
      grid.rect(x, y, w-unit(0.5, "mm"), h*0.47, vjust = 0, gp = gpar(fill = "#FB9A99", col = NA))
    },
    C2 = function(x, y, w, h) {
      grid.rect(x, y, w-unit(0.5, "mm"), h*0.47, vjust = 1, gp = gpar(fill = "#E31A1C", col = NA))
    }
  )
```

```{r}
class <- c("A1", "A2", "B1", "B2", "C1", "C2")
hla.melt <- melt(hla, id.vars = c("subject")) %>% 
      mutate_at(.vars = c("subject","variable"), .funs = as.character) 
hla.cast <- dcast(hla.melt, value~subject, value.var = "variable", fun.aggregate = function(x) paste(x, collapse = ";")) %>%
  rename("hla"="value")

##gene order
hla.class1 <- hla.cast
hla.class1 <- hla.class1 %>%
  # count non-empty strings row-wise
  mutate(non_empty_count = pmap_int(select(., -hla), ~ sum(c(...) != ""))) %>%
  arrange(desc(non_empty_count)) %>%
  top_n(n = 15) %>%
  select(-non_empty_count) %>%
  column_to_rownames("hla") %>%
  select(where(~ any(.x != "")))

hla.expr.aver <- colMeans(hla.expr)


# prioritize columns based on two things:
# High number of non-empty cells
# those non-empty cells are concentrated toward the top
# we want the "densest & top-loaded" columns to come first

# create a scoring function
score_column <- function(x) {
  positions <- which(x != "")
  non_empty_count <- length(positions)
  top_bias <- sum(1 / positions)  # gives more weight to top rows
  
  # combine both: you can tweak the weight (e.g., 0.7 for top bias, 0.3 for count)
  score <- 0.7 * top_bias + 0.3 * non_empty_count
  return(score)
}

# apply scoring across columns
column_scores <- map_dbl(hla.class1, score_column)

# sort columns by descending score
hla.class1_sorted <- hla.class1[, order(-column_scores)]

#check the order
top_anno1 <- meta %>%
  filter(subject %in% colnames(hla.class1_sorted)) %>%
  arrange(match(subject, colnames(hla.class1_sorted))) %>%
  pull(group)
top_anno2 <- meta %>%
  filter(subject %in% colnames(hla.class1_sorted)) %>%
  arrange(match(subject, colnames(hla.class1_sorted))) %>%
  pull(dataset)
```


order within group
```{r}
# create a scoring function
score_column <- function(x) {
  positions <- which(x != "")
  non_empty_count <- length(positions)
  top_bias <- sum(1 / positions)  # gives more weight to top rows
  
  # combine both: you can tweak the weight (e.g., 0.7 for top bias, 0.3 for count)
  score <- 0.7 * top_bias + 0.3 * non_empty_count
  return(score)
}

# apply scoring across columns
column_scores <- map_dbl(hla.class1, score_column)

group_info <- deframe(meta)

# 4. Create data frame with column, group, and score
col_meta <- data.frame(
  sample = colnames(hla.class1),
  group = group_info[colnames(hla.class1)],
  score = column_scores
)

# 5. Sort within each group by score
sorted_samples <- col_meta %>%
  group_by(group) %>%
  arrange(desc(score), .by_group = TRUE) %>%
  pull(sample)

# 6. Reorder columns
hla.class1_sorted <- hla.class1[, sorted_samples]

#check the order
top_anno1 <- meta %>%
  filter(subject %in% colnames(hla.class1_sorted)) %>%
  arrange(match(subject, colnames(hla.class1_sorted))) %>%
  pull(group)

top_anno2 <- meta %>%
  filter(subject %in% colnames(hla.class1_sorted)) %>%
  arrange(match(subject, colnames(hla.class1_sorted))) %>%
  pull(dataset)
```

```{r}
col_fun <- structure(
  c("#A6CEE3", "#B2DF8A", "#FB9A99", "#1F78B4", "#33A02C", "#E31A1C"),
  names = c("A1", "B1", "C1", "A2", "B2", "C2")
)

ht_list <- oncoPrint(hla.class1_sorted, get_type = function(x) strsplit(x, ";")[[1]],
                     alter_fun_is_vectorized = FALSE,
                     alter_fun = alter_fun, col = col_fun,
                     row_names_gp = gpar(fontsize = 10,fontface = "bold"),
                     pct_gp = gpar(fontsize = 10,fontface = "bold"),
                     remove_empty_columns = FALSE,
                     show_column_names = FALSE, 
                     column_order = colnames(hla.class1_sorted),
                     row_order = rownames(hla.class1_sorted),
                     top_annotation = 
                       HeatmapAnnotation(
                         HLA_Expression=anno_points(hla.expr.aver[colnames(hla.class1_sorted)]),
                         "Response" = top_anno1,
                         "Dataset" = top_anno2,
                         col = list("Response" = c("R"="#d5b3ff",
                                                      "NR"="#fbd960"),
                                    "Dataset" = c("Hugo-2016"="#e0be36",
                                                  "Riaz-2017"="#00a0d1",
                                                  "Auslander-2018"="#C8DE7B",
                                                  "Gide-2019"="#fb6f92",
                                                  "Du-2021"="#e07a5f")),
                         annotation_name_gp = gpar(fontsize = 8),
                         annotation_legend_param = list(
                           title_gp = gpar(fontsize = 10, fontface = "bold") )
                         ),
                     
                     heatmap_legend_param = list(title = "Allele",
                                                 ncol=2,
                                                 at = names(col_fun),
                                                 labels = names(col_fun),
                                                 legend_gp = gpar(fill = col_fun),
                                                 grid_height = unit(6, "mm")))
ht_list

ht_list@top_annotation@anno_list[["Sample Type"]]@name_param[["show"]] <- FALSE
ht_list@top_annotation@anno_list[["Dataset"]]@name_param[["show"]] <- FALSE

ht_list


png(file.path(main_folder,"visualizations_immunotherapy_dataset/hla_overview_02.png"), width = 3500, height = 2000, res = 300)
ht_list
dev.off()
```

```{r}
hla_encoded <- hla %>%
  filter(subject %in% colnames(hla.class1)) %>%
  arrange(match(subject, colnames(hla.class1))) %>%
  model.matrix(~ . - subject - 1, data = .)
rownames(hla_encoded) <- colnames(hla.class1)

dist_mat <- dist(hla_encoded, method = "binary")
hc <- hclust(dist_mat, method = "ward.D2")
plot(hc)

hc$labels[hc$order]
sorted_samples <- rownames(hla_encoded)[hc$order]


hla.class1_sorted <- hla.class1[, sorted_samples]
top_anno1 <- meta %>%
  filter(subject %in% colnames(hla.class1_sorted)) %>%
  arrange(match(subject, colnames(hla.class1_sorted))) %>%
  pull(group)
top_anno2 <- meta %>%
  filter(subject %in% colnames(hla.class1_sorted)) %>%
  arrange(match(subject, colnames(hla.class1_sorted))) %>%
  pull(dataset)


within_group <- meta %>%
  filter(subject %in% colnames(hla.class1)) %>%
  group_by(group) %>%
  arrange(match(subject, sorted_samples), .by_group = TRUE) %>%
  ungroup() %>%
  pull(subject)
hla.class1_sorted <- hla.class1[, within_group]

top_anno1 <- meta %>%
  filter(subject %in% colnames(hla.class1_sorted)) %>%
  arrange(match(subject, colnames(hla.class1_sorted))) %>%
  pull(group)

top_anno2 <- meta %>%
  filter(subject %in% colnames(hla.class1_sorted)) %>%
  arrange(match(subject, colnames(hla.class1_sorted))) %>%
  pull(dataset)
```

```{r}
col_fun <- structure(
  c("#A6CEE3", "#B2DF8A", "#FB9A99", "#1F78B4", "#33A02C", "#E31A1C"),
  names = c("A1", "B1", "C1", "A2", "B2", "C2")
)

ht_list <- oncoPrint(hla.class1_sorted, get_type = function(x) strsplit(x, ";")[[1]],
                     alter_fun_is_vectorized = FALSE,
                     alter_fun = alter_fun, col = col_fun,
                     row_names_gp = gpar(fontsize = 10,fontface = "bold"),
                     pct_gp = gpar(fontsize = 10,fontface = "bold"),
                     remove_empty_columns = FALSE,
                     show_column_names = FALSE, 
                     column_order = colnames(hla.class1_sorted),
                     row_order = rownames(hla.class1_sorted),
                     top_annotation = 
                       HeatmapAnnotation(
                         HLA_Expression=anno_points(hla.expr.aver[colnames(hla.class1_sorted)]),
                         "Response" = top_anno1,
                         "Dataset" = top_anno2,
                         col = list("Response" = c("R"="#d5b3ff",
                                                      "NR"="#fbd960"),
                                    "Dataset" = c("Hugo-2016"="#e0be36",
                                                  "Riaz-2017"="#00a0d1",
                                                  "Auslander-2018"="#C8DE7B",
                                                  "Gide-2019"="#fb6f92",
                                                  "Du-2021"="#e07a5f")),
                         annotation_name_gp = gpar(fontsize = 8),
                         annotation_legend_param = list(
                           title_gp = gpar(fontsize = 10, fontface = "bold") )
                         ),
                     
                     heatmap_legend_param = list(title = "Allele",
                                                 ncol=2,
                                                 at = names(col_fun),
                                                 labels = names(col_fun),
                                                 legend_gp = gpar(fill = col_fun),
                                                 grid_height = unit(6, "mm")))
ht_list

ht_list@top_annotation@anno_list[["Response"]]@name_param[["show"]] <- FALSE
ht_list@top_annotation@anno_list[["Dataset"]]@name_param[["show"]] <- FALSE

ht_list


png(file.path(main_folder,"visualizations_immunotherapy_dataset/hla_overview_04.png"), width = 3700, height = 2000, res = 300)
ht_list
dev.off()
```


#---------------------------------------------------------------------
HED heatmap
```{r}
suppressPackageStartupMessages({
  library(here)
  library(tidyverse)
  library(ComplexHeatmap)
  library(circlize)
  
  library(rstatix)
  library(ggpubr)
})
main_folder <- here()
```

```{r}
hed <- read_tsv(file.path(main_folder,"HED.tsv"), show_col_types=F) %>%
  column_to_rownames("patient") %>%
  select(-mean)

coldata <- read_csv(file.path(main_folder,"clean_metadata.csv"), show_col_types=F)
```

```{r}
### Vertical Heatmap

# col = colorRamp2(
#   c(0, 2, 4, 6, 8, 10, 12, 14),
#   c("#ffba08","#faa307","#f48c06","#e85d04","#dc2f02","#d00000","#9d0208","#6a040f")
# )
# 
# min_per_column <- as.data.frame(apply(hed,2,min))
# max_per_column <- as.data.frame(apply(hed,2,max))
# 
# 
# left_ha <- rowAnnotation(Dataset = coldata$dataset,
#                             Response = coldata$response_group,
#                             col = list(Dataset = c("Hugo-2016"="#e0be36",
#                                                   "Riaz-2017"="#00a0d1",
#                                                   "Auslander-2018"="#C8DE7B",
#                                                   "Gide-2019"="#fb6f92",
#                                                   "Du-2021"="#e07a5f"),
#                                        "Response" = c("R"="#d5b3ff",
#                                                       "NR"="#fbd960")),
#                         annotation_legend_param = list(Dataset = list(nrow = 5, title = "Dataset", title_gp = gpar(fontsize = 12, fontface = "bold")),
#                                                        Response = list(nrow = 2, title = "Response", title_gp = gpar(fontsize = 12, fontface = "bold")))
#                         )
# 
# max_width_cm <- 5
# cell_width <- max_width_cm / nrow(hed)
# 
# htmp <- draw(Heatmap(hed,
#              col = col, show_column_names = T, show_row_names = F,
#              cluster_rows = T, cluster_columns = F,
#              show_column_dend = T,
#              name = "HED",
#              #row_split = coldata$group.a,
#              row_title = NULL,
#              #top_annotation = top_ha,
#              left_annotation = left_ha,
#              column_names_rot = 0, column_names_centered = T,
#              rect_gp = gpar(col = "white", lwd = 0.3),
#              border_gp = gpar(col = "#7f7f7f"),
#              width = unit(ncol(hed) * 0.6, "cm"),    # <- controls column width
#              height = unit(nrow(hed) * 0.2, "cm"),   # <- controls row height
#              heatmap_legend_param = list(legend_direction="vertical", 
#                                          at = c(0, 2, 4, 6, 8, 10, 12, 14),
#                                          #legend_width = unit(5, "cm"),
#                                          #legend_height = unit(3.8, "cm"),
#                                          #grid_width = unit(0.5, "cm"),
#                                          #grid_height = unit(0.5, "cm"),
# 
#                                          title_position = "topcenter",
#                                          title_gp = gpar(fontsize = 12, fontface = "bold")),
#              border = TRUE), 
#              heatmap_legend_side="right", merge_legend = T)
# 
# 
# cell_size_px <- 30
# # calculate image dimensions
# width_px <- ncol(hed) * cell_size_px + 800   # + space for legends/annotations
# height_px <- nrow(hed) * cell_size_px + 300  # adjust margin buffer as needed
# 
# png(file.path(main_folder,"visualizations_immunotherapy_dataset/hed_heatmap2.png"), width = width_px, height = height_px, res = 300)
# htmp
# dev.off()
```

```{r}
col = colorRamp2(
  c(0, 2, 4, 6, 8, 10, 12, 14),
  c("#ffba08","#faa307","#f48c06","#e85d04","#dc2f02","#d00000","#9d0208","#6a040f")
)

min_per_column <- as.data.frame(apply(hed,2,min))
max_per_column <- as.data.frame(apply(hed,2,max))


top_ha <- columnAnnotation(Dataset = coldata$dataset,
                            Response = coldata$response_group,
                            col = list(Dataset = c("Hugo-2016"="#e0be36",
                                                  "Riaz-2017"="#00a0d1",
                                                  "Auslander-2018"="#C8DE7B",
                                                  "Gide-2019"="#fb6f92",
                                                  "Du-2021"="#e07a5f"),
                                       "Response" = c("R"="#d5b3ff",
                                                      "NR"="#fbd960")),
                        annotation_legend_param = list(Dataset = list(nrow = 5, title = "Dataset", title_gp = gpar(fontsize = 12, fontface = "bold")),
                                                       Response = list(nrow = 2, title = "Response", title_gp = gpar(fontsize = 12, fontface = "bold")))
                        )

htmp <- draw(Heatmap(t(hed),     #  << transpose here
             col = col, show_column_names = F, show_row_names = T,
             cluster_rows = F, cluster_columns = T,
             show_column_dend = T,
             name = "HED",
             #column_split = coldata$response_group,
             column_split = coldata$dataset,
             column_title = NULL,
             top_annotation = top_ha,
             #column_names_rot = 0, column_names_centered = T,
             rect_gp = gpar(col = "white", lwd = 0.3),
             border_gp = gpar(col = "#7f7f7f"),
             width = unit(nrow(hed) * 0.21, "cm"),
             height = unit(ncol(hed) * 1, "cm"),
             heatmap_legend_param = list(legend_direction="horizontal",   #  <<< legend horizontal
                                         at = c(0, 2, 4, 6, 8, 10, 12, 14),
                                         #legend_width = unit(5, "cm"),
                                         #legend_height = unit(3.8, "cm"),
                                         #grid_width = unit(0.5, "cm"),
                                         #grid_height = unit(0.5, "cm"),

                                         title_position = "topcenter",
                                         title_gp = gpar(fontsize = 12, fontface = "bold")),
             border = TRUE), 
             heatmap_legend_side= "bottom",       #  <<< move legend under
             merge_legend = TRUE
)


cell_size_px <- 25
# calculate image dimensions
width_px <- nrow(hed) * cell_size_px + 300
height_px <- ncol(hed) * cell_size_px + 1000 

png(file.path(main_folder,"visualizations_immunotherapy_dataset/hed_heatmap_03.png"), width = width_px, height = height_px, res = 300)
htmp
dev.off()

```



```{r}
coldata <- read_csv(file.path(main_folder,"clean_metadata.csv"), show_col_types=F) %>%
  select(-response) %>%
  rename("response"="response_group") %>%
  mutate(enrichment_protocol = ifelse(is.na(enrichment_protocol), "unspecified", enrichment_protocol))

#function to compute statistics 
fix_data <- function(data) {
  dd <- data %>% 
    pivot_longer(!Group, names_to = "Vars") %>% 
    inner_join(coldata, by = join_by(Vars == accession))
  stat <- list()
  for (hla in unique(dd$Group)) {
    #response
    aa <- dd %>% filter(Group == hla)
    aa$response <- factor(aa$response, levels = c("NR","R"))
    stat.test_NR_R <- aa %>%
      filter(response %in% c("NR","R")) %>%
      t_test(value ~ response, detailed = TRUE) %>%
      adjust_pvalue(method = "BH") %>%
      add_xy_position(x = "response", fun = "mean_se") %>% 
      mutate(p.adj.signif=ifelse(p<=0.05,"*","ns")) %>% 
      mutate(p.adj.signif=ifelse(p<=0.005,"**",p.adj.signif))
    
    #protocol
    aa <- dd %>% filter(Group == hla)
    aa$enrichment_protocol <- factor(aa$enrichment_protocol, levels = c("polyA-selection", "rRNA-depletion"))
    stat.test_POLYA_RIBOZ <- aa %>%
      filter(enrichment_protocol %in% c("polyA-selection","rRNA-depletion")) %>% 
      t_test(value ~ enrichment_protocol, detailed = TRUE) %>%
      adjust_pvalue(method = "BH") %>%
      add_xy_position(x = "enrichment_protocol", fun = "mean_se") %>% 
      mutate(p.adj.signif=ifelse(p<=0.05,"*","ns")) %>% 
      mutate(p.adj.signif=ifelse(p<=0.005,"**",p.adj.signif))
    aa <- dd %>% filter(Group == hla)
    aa$enrichment_protocol <- factor(aa$enrichment_protocol, levels = c("polyA-selection", "targeted-mRNA-capture"))
    stat.test_POLYA_TARGETED <- aa %>%
      filter(enrichment_protocol %in% c("polyA-selection", "targeted-mRNA-capture")) %>% 
      t_test(value ~ enrichment_protocol, detailed = TRUE) %>%
      adjust_pvalue(method = "BH") %>%
      add_xy_position(x = "enrichment_protocol", fun = "mean_se") %>% 
      mutate(p.adj.signif=ifelse(p<=0.05,"*","ns")) %>% 
      mutate(p.adj.signif=ifelse(p<=0.005,"**",p.adj.signif))
    aa <- dd %>% filter(Group == hla)
    aa$enrichment_protocol <- factor(aa$enrichment_protocol, levels = c("polyA-selection", "unspecified"))
    stat.test_POLYA_UNK <- aa %>%
      filter(enrichment_protocol %in% c("polyA-selection", "unspecified")) %>% 
      t_test(value ~ enrichment_protocol, detailed = TRUE) %>%
      adjust_pvalue(method = "BH") %>%
      add_xy_position(x = "enrichment_protocol", fun = "mean_se") %>% 
      mutate(p.adj.signif=ifelse(p<=0.05,"*","ns")) %>% 
      mutate(p.adj.signif=ifelse(p<=0.005,"**",p.adj.signif))
    aa <- dd %>% filter(Group == hla)
    aa$enrichment_protocol <- factor(aa$enrichment_protocol, levels = c("rRNA-depletion", "unspecified"))
    stat.test_RIBOZ_UNK <- aa %>%
      filter(enrichment_protocol %in% c("rRNA-depletion", "unspecified")) %>% 
      t_test(value ~ enrichment_protocol, detailed = TRUE) %>%
      adjust_pvalue(method = "BH") %>%
      add_xy_position(x = "enrichment_protocol", fun = "mean_se") %>% 
      mutate(p.adj.signif=ifelse(p<=0.05,"*","ns")) %>% 
      mutate(p.adj.signif=ifelse(p<=0.005,"**",p.adj.signif))
    stat.test <- rbind.data.frame(stat.test_NR_R, stat.test_POLYA_RIBOZ, stat.test_POLYA_TARGETED, stat.test_POLYA_UNK, stat.test_RIBOZ_UNK)
    
    stat.test <- stat.test %>% 
      mutate(xmin = case_when(
        group1 == "NR" & group2 == "R" ~ 1,
        group1 == "polyA-selection" & group2 == "rRNA-depletion" ~ 3,
        group1 == "polyA-selection" & group2 == "targeted-mRNA-capture" ~ 3,
        group1 == "polyA-selection" & group2 == "unspecified" ~ 3,
        group1 == "rRNA-depletion" & group2 == "unspecified" ~ 4
      ),
      xmax = case_when(
        group1 == "NR" & group2 == "R" ~ 2,
        group1 == "polyA-selection" & group2 == "rRNA-depletion" ~ 4,
        group1 == "polyA-selection" & group2 == "targeted-mRNA-capture" ~ 5,
        group1 == "polyA-selection" & group2 == "unspecified" ~ 6,
        group1 == "rRNA-depletion" & group2 == "unspecified" ~ 6
      )) 
    stat[[hla]] <- stat.test
  }
  return(stat)
}


#boxplot
plot_pop <- function(data, stats, ypos, hla) {
  dd <- data %>% 
    pivot_longer(!Group, names_to = "Vars") %>% 
    inner_join(coldata, by = join_by(Vars == accession))
  
  response <- dd %>%
    select(Group,Vars,value,response,dataset) %>%
    rename("type"="response")
  protocol <- dd %>%
    select(Group,Vars,value,enrichment_protocol,dataset) %>%
    rename("type"="enrichment_protocol")
  df <- rbind(response,protocol) %>%
    subset(Group == hla)
  
  df$type <- factor(df$type, levels = c("NR", "R", "polyA-selection", "rRNA-depletion", "targeted-mRNA-capture", "unspecified"))
  

  ggplot(df, aes(x=type, y=value)) + 
    ggtitle(hla) + 
    stat_boxplot(geom = "errorbar", width = 0.2, aes(color = type), show.legend = F) +
    geom_boxplot(size = 0.7, width = 0.3, aes(color = type), outlier.colour = NA, alpha=0.1, show.legend = F) +
    geom_jitter(width = 0.1, size = 2, aes(color = type), alpha = 0.2, show.legend = F) +
    labs(x = "", y = "CIBERSORTx Absolute values", title = paste0("HED for ", hla)) +
    theme(plot.title = element_text(size = 14, hjust = 0.5, face = "bold.italic"),
            plot.margin = margin(5,5,5,5), aspect.ratio = 1,
            axis.text.y = element_text(size = 12 , color = "black"),
            axis.text.x = element_text(face = "bold", size = 10, hjust = 0.5),
            axis.title.y = element_text(size = 14, face = "bold", margin = margin(r = 10)),
            panel.background = element_rect(fill="white"),
            panel.grid = element_line(colour = "#f5f2f2"),
            panel.border = element_rect(colour = "#383636", fill=NA, size=1), 
            legend.title = element_blank(),
            strip.text.x = element_text(size = 8, face = "bold.italic"),
            strip.background = element_rect(fill="white")) +
    scale_color_manual(values = c("R"="#d5b3ff",
                                  "NR"="#fbd960",
                                  "polyA-selection"="#6a8532",
                                  "targeted-mRNA-capture"="#d95d39",
                                  "rRNA-depletion"="#6a4c93",
                                  "unspecified"="#c9ada7")) +
    #stat_pvalue_manual(stats, hide.ns = T, label = "p.adj.signif", tip.length = 0, y.position = ypos)
    stat_pvalue_manual(stats, hide.ns = T, label = "p.adj.signif", tip.length = 0) + 
    scale_x_discrete(labels = c("R" = "R",
                                "NR" = "NR",
                                "polyA-selection" = "PolyA",
                                "targeted-mRNA-capture" = "Targeted",
                                "rRNA-depletion" = "Ribo",
                                "unspecified" = "UNK")
                     )
}

```


```{r}
data <- hed %>%
  rename("HLA-A"="A", "HLA-B"="B", "HLA-C"="C") %>%
  t(.) %>%
  as.data.frame(.) %>%
  rownames_to_column("Group")

stats <- fix_data(data)
p1 <- plot_pop(data, hla = "HLA-C", stats = stats$`HLA-C`)
p1
p2 <- plot_pop(data, hla = "HLA-B", stats = stats$`HLA-B`)
p2
p3 <- plot_pop(data, hla = "HLA-A", stats = stats$`HLA-A`)
p3

# Loop to save each plot
for (i in 1:3) {
  plot_name <- paste0("p", i)
  file_name <- paste0(file.path(main_folder,"visualizations_immunotherapy_dataset/hed_boxplot"), i, ".png")
  
  png(file_name, width = 2500, height = 1500, res = 300)
  print(get(plot_name))
  dev.off()
}
```


